---
# tasks file for postgresql

- name: backup | Create backup directory
  file:
    path: /backup
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'

- name: backup | Template backup.sh to /usr/local/bin
  template:
    src: backup.sh.j2
    dest: backup.sh
    owner: root
    group: root
    mode: '0644'

- name: backup | Template backup.service to /etc/systemd/system
  template:
    src: backup.service.j2
    dest: backup.service
    owner: root
    group: root
    mode: '0644'

- name: backup | Template backup.timer to /etc/systemd/system
  template:
    src: backup.timer.j2
    dest: backup.timer
    owner: root
    group: root
    mode: '0644'