---
# tasks file for postgresql

- name: master | Initialization postgresql database
  command: postgresql-14-setup initdb

#listen_addresses = 'localhost'         # what IP address(es) to listen on;
- name: master | Edit postgresql.conf
  lineinfile:
    path: /var/lib/pgsql/14/data/postgresql.conf
    regexp: '^(.*)#listen_addresses = 'localhost'(.*)$'
    line: 'listen_addresses = \'*\''
    backrefs: yes
  tags:
  - pg_conf

#host    all             all             127.0.0.1/32            scram-sha-256
- name: master | Edit pg_hba.conf 1
  lineinfile:
    path: /var/lib/pgsql/14/data/pg_hba.conf
    regexp: '^(.*)host    all             all             127.0.0.1/32            scram-sha-256(.*)$'
    line: 'host    all             all             0.0.0.0/00            scram-sha-256'
    backrefs: yes

#host    replication     all             127.0.0.1/32            scram-sha-256
- name: master | Edit pg_hba.conf 2
  lineinfile:
    path: /var/lib/pgsql/14/data/pg_hba.conf
    regexp: '^(.*)host    replication     all             127.0.0.1/32            scram-sha-256(.*)$'
    line: 'host    replication     all             0.0.0.0/00            scram-sha-256'
    backrefs: yes

- name: Start postgresql service
    systemd:
      name: postgresql-14
      state: restarted
      enabled: yes

- name: Change password for user 'postgres'
  expect:
    command: passwd postgres
    responses:
      (?i)password: "psql@Otus1234"
  # you don't want to show passwords in your logs
  no_log: true

#- name: create repl user
#  shell: su - postgres -c "createuser --replication -P repl"
#      timeout: null
#      responses: 
#        '.*Enter password for new role.*': "Otus1234"
#        '.*Enter it again.*': "Otus1234"







